# Generated by Django 4.0.4 on 2022-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0002_student_firstname_student_lastname_student_testscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sal', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='testScore',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('programmers', models.ManyToManyField(to='fbvApp.programmer')),
            ],
        ),
    ]
